version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:7.4-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

